### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by KMayne** [jivanpal/drat#15]
For offline recovery, it might be helpful to have this tool available on Linux. 
Currently the build fails due to printf format string issues as well as relying on some non-portable C functions.
I managed to hack it and get it to build successfully on Ubuntu 20.04 on a branch on my fork: https://github.com/KMayne/drat/tree/ubuntu-build

**Comment by jivanpal** [comment]
Thanks for reporting this. I intend to test builds consistently on other platforms in the future, probably after 0.2.0 is released (ETA, 1 month or so). Binaries for those platforms should follow.

- Thanks for bringing my attention to `<inttypes.h>`, I will definitely switch to using that!
- I didn't realise that `asprintf()` etc. were GNU extensions, but documentation shows that defining `_GNU_SOURCE` suffices to have them compile from `<stdio.h>`, so no need to borrow source code.
- The `strcasecmp()` function is in `<strings.h>` per POSIX, but macOS also includes `<strings.h>` in `<string.h>` for historical reasons, so I never noticed.
- Rather than using a modified `<sys/stat.h>`, I have renamed `mode_t` and defined the BSD flags from `chflags(2)`.

I have made needed changes on a new branch `portable-test` and tested them on Ubuntu 20.04. If you could checkout that branch and also test compilation, I'd appreciate it 🙂

**Comment by KMayne** [comment]
Awesome, this compiles with no problems for me. I'm not very familiar with POSIX so thanks for explaining :)
I would have been keen to contribute more but sadly I discovered my entire disk was somehow completely zeroed which left my motivation similarly zeroed 🙃

**Comment by jivanpal** [comment]
Ouch... in any case, thanks for this — closing now.
